# ----------------------------------------------------------
# project: doxygen by Dimitri van Heesh
# autor:   2025 Jens Kallup <paule32.jk@gmail.com>
#
# desc:    this workflow provides some translations for the
#          doxygen project.
#          The files that are created by this workflow file
#          can be used platform independed, so no need for
#          more workflows for translations.
# ----------------------------------------------------------
name: Build Locales for Doxygen

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install gettext
      run: sudo apt-get install -y gettext

    - name: Compile Translations (English)
      run: |
        mkdir  -p src/en/LC_MESSAGES
        msgfmt -o src/en/LC_MESSAGES/messages.mo src/en.po
        mkdir -p locale/en/LC_MESSAGES
        cp src/en/LC_MESSAGES/messages.mo locale/en/LC_MESSAGES/messages.mo
    
    - name: Compile Translations (German)
      run: |
        mkdir  -p src/de/LC_MESSAGES
        msgfmt -o src/de/LC_MESSAGES/messages.mo locale/de.po
        mkdir -p locale/de/LC_MESSAGES
        cp src/de/LC_MESSAGES/messages.mo locale/de/LC_MESSAGES/messages.mo
        
    - name: Create Archive
      run: |
        mkdir -p build_artifacts
        cp -r locale build_artifacts/
        tar -czvf build_artifacts/translations.tar.gz locale/
        
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-translations
        path: build_artifacts/
